version: '3'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    restart: always

  wordpress:
    build: ./requirements/wordpress
    depends_on:
      - mariadb
    image: wordpress
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    ports:
      - "9000:9000"
    volumes:
      - wp-data:/www/wordpress
    networks:
      - app-network
    restart: always

  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx_container
    ports:
      - "443:443"
    networks:
      - app-network
    volumes:
      - wp-data:/www/wordpress
    restart: always

  redis:
    build: ./requirements/bonus/redis
    depends_on:
      - wordpress
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - wp-data:/www/wordpress
    networks:
      - app-network
    restart: always
    
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    ports:
      - "6060:6060"
    networks:
      - app-network
    restart: always

  grafana:
    build: ./requirements/bonus/grafana
    image: grafana
    ports:
      - "3000:3000"
      - "8086:8086"
    networks:
      - app-network
    restart: always

  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    env_file: .env
    ports:
      - "21:21"
      - "20000:20000"
    volumes:
      - wp-data:/home/sqatim/wordpress
    networks:
      - app-network
    restart: always

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: 'bind' #option
      device: /home/sqatim/data/wordpress
  db-data:
    driver: local
    driver_opts:
      type: none
      o: 'bind' #option
      device: /home/sqatim/data/mariadb
    

networks:
  app-network:
    driver: bridge
